name: PRs auto merge

on:
  schedule:
    # Every friday every hour between 12 and 15 UTC
    - cron: "0 12-15 * * 5"

jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: 'squash' # Default 'squash'
        min-approvals: 2 # Default 2
        base-ref: 'dev' # Default 'dev'
